// MeanMedian.Java - Iakov Taranenko - 3/30/2021

/* 

Programming Exercise 9-2A

The mean of a list of numbers is its arithmetic average. The median of a list is its middle value when the values are placed in order. For example, if an ordered list contains 1, 2, 3, 4, 5, 6, 10, 11, and 12, then the mean is 6, and their median is 5. Write an application that allows you to enter nine integers and displays the values, their mean, and their median.

An example of the program is shown below:

...
Enter number 6
12
Enter number 7
14
Enter number 8
16
Enter number 9
18
You entered: 2,  4,  6,  8,  10,  12,  14,  16,  18
The mean is 10.0 and the median is 10

The example above is abbreviated and included for guidance and does not include all the information generated by the program.

*/

import java.util.*;
class MeanMedian {
    public static void main(String[] args) {
        // your code here
    }
}